import numpy as np
from src.utils import Discretizer

WIRELESS_CONFIG = {
    "gamma": 0.9,
    "num_experiments": 1,
    "num_processes": 1,
    "E": 500,
    "H": 200,
    "lr": 0.01,
    "eps": 1.0,
    "eps_decay": 0.9999,
    "eps_min": 0.001,
    "k": 50,
    "n_upd": 4,

    "env_params": [
        {
            "batt_harvest": 0.5,
            "queue_arrival": 1.0,
            "P_harvest": 0.2,
            "P_arrival": 0.2,
            "T": 200,  # H
            "K": 1,
            "snr_max": 5,
            "snr_min": 5,
            "snr_autocorr": 0.7,
            "P_occ": np.array([[0.8, 0.2], [0.2, 0.8]]),
            "occ_initial": [1],
            "batt_initial": 10,
            "batt_max_capacity": 10,
            "batt_weight": 1.5,
            "queue_initial": 2,
            "queue_max_capacity": 10,
            "t_queue_arrival": 0,
            "queue_weight": 0.5,
            "loss_busy": 1.0
        },
        {
            "batt_harvest": 0.5,
            "queue_arrival": 1.0,
            "P_harvest": 0.5,
            "P_arrival": 0.2,
            "T": 200,
            "K": 1,
            "snr_max": 5,
            "snr_min": 5,
            "snr_autocorr": 0.7,
            "P_occ": np.array([[0.8, 0.2], [0.2, 0.8]]),
            "occ_initial": [1],
            "batt_initial": 10,
            "batt_max_capacity": 10,
            "batt_weight": 1.5,
            "queue_initial": 2,
            "queue_max_capacity": 10,
            "t_queue_arrival": 0,
            "queue_weight": 0.5,
            "loss_busy": 1.0
        },
        {
            "batt_harvest": 0.5,
            "queue_arrival": 1.0,
            "P_harvest": 0.5,
            "P_arrival": 0.5,
            "T": 200,
            "K": 1,
            "snr_max": 5,
            "snr_min": 5,
            "snr_autocorr": 0.7,
            "P_occ": np.array([[0.8, 0.2], [0.2, 0.8]]),
            "occ_initial": [1],
            "batt_initial": 10,
            "batt_max_capacity": 10,
            "batt_weight": 1.5,
            "queue_initial": 2,
            "queue_max_capacity": 10,
            "t_queue_arrival": 0,
            "queue_weight": 0.5,
            "loss_busy": 1.0
        },
        {
            "batt_harvest": 3.0,
            "queue_arrival": 2.0,
            "P_harvest": 0.8,
            "P_arrival": 0.8,
            "T": 200,
            "K": 1,
            "snr_max": 5,
            "snr_min": 5,
            "snr_autocorr": 0.7,
            "P_occ": np.array([[0.8, 0.2], [0.2, 0.8]]),
            "occ_initial": [1],
            "batt_initial": 10,
            "batt_max_capacity": 10,
            "batt_weight": 1.5,
            "queue_initial": 2,
            "queue_max_capacity": 10,
            "t_queue_arrival": 0,
            "queue_weight": 0.5,
            "loss_busy": 1.0
        }
    ],

    "discretizer": Discretizer(
        min_points_states=[0, 0, 0, 0],
        max_points_states=[20, 1, 10, 10],
        bucket_states=[20, 2, 10, 10],
        min_points_actions=[0],
        max_points_actions=[2],
        bucket_actions=[10],
    )
}
